kind: Secret
apiVersion: v1
metadata:
  name: htpass-beginner
  namespace: openshift-config
data:
  htpasswd: dXNlcjAxOiQyeSQwNSRHRTNVdmJFMTkuLjVneDFVc3d0MnRPV1JMNUZsb0Zya1lma0pHczdrRU1vdTNpTlJVN1JULgphZG1pbjAxOiQyeSQwNSRjNUs4d1ZLZ0lIZkR3bjZpRkFDcHlldjh3VHlPZU9QU05La2NINGNacGJhZ0huOTNEZmt5Qw==
type: Opaque
